language: php
php:
  - 5.4
  - 5.3
services:
  - mongodb
before_script:
  - pecl install --soft mongo
  - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer --dev --prefer-source install