language: php
php:
  - 5.4
  - 5.3
env:
  - MONGO_VERSION=1.3.3
  - MONGO_VERSION=1.3.4
services:
  - mongodb
before_script:
  - pecl -q install mongo-${MONGO_VERSION} && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install --dev --prefer-source